version: "3.8"
services: 
  mongodb:
    image: mongo
    volumes: 
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dockermongo
      MONGO_INITDB_ROOT_PASSWORD: dockermongo
  backend:
    build: ./backend
    ports: 
      - '80:80'
    environment:
      MONGO_INITDB_ROOT_USERNAME: dockermongo
      MONGO_INITDB_ROOT_PASSWORD: dockermongo
    depends_on: 
      - mongodb

  frontend:
    build: ./frontend
volumes: 
  data:
    